name: Merge - Build and Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - ob-v*
    paths-ignore:
      - '**/README.md'
env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
jobs:
  run_merge-template:
    name: Merge - Build and Deploy
    uses: SecureApiGateway/secure-api-gateway-ci/.github/workflows/reusable-merge.yml@main
    secrets: inherit
    with:
      componentName: secure-api-gateway-core
      dockerTag: $(echo ${{ github.sha }} | cut -c1-7)
      branch: ${{ env.BRANCH_NAME }}