name: PR - Build and Deploy
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/README.md'
jobs:
  run_pr-template:
    name: PR - Build and Deploy
    # NOTE: Revert before merging
    uses: SecureApiGateway/secure-api-gateway-ci/.github/workflows/reusable-pr.yml@1472-use-latest-ig-in-sapig
    secrets: inherit
    with:
      componentName: secure-api-gateway-core
      dockerTag: pr-${{ github.event.number }}