name: Pull Request Build and Deploy

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/README.md'

jobs:
  run_pr-template:
    name: PR Workflow
    uses: SecureApiGateway/secure-api-gateway-ci/.github/workflows/pr-template.yml@1389-standard-steps-for-workflows
    with:
      componentName: secure-api-gateway-core