name: Pull Request Build and Deploy

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/README.md'

env:
  PR_NUMBER: pr-${{ github.event.number }}
  SERVICE_NAME: ig
  CF_TRIGGER_NAME: github-actions-trigger-gateway
  CF_PIPELINE_NAME: SAPIG-devenv/dev-ob-service-build
  CF_PIPELINE_BRANCH: main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Checkout CI Code 
        uses: actions/checkout@v4
        with: 
          repository: SecureApiGateway/secure-api-gateway-ci
          path: secure-api-gateway-ci
      # Auth GCP, SDK & Artifact Registry
      - name: Call Authentication
        uses: ./.github/actions/authentication
        with: 
          garKey: ${{ secrets.DEV_GAR_KEY }}
          garURL: ${{ vars.GAR_LOCATION }}      
      # Set Java and Cache
      - name: Set Java and Maven Cache
        uses: actions/setup-java@v4
        id: set_java_maven
        with:
          distribution: 'zulu'
          java-version: '17'
          architecture: x64
          cache: 'maven'
          server-id: forgerock-internal-releases # protected release repo
          server-username: FR_ARTIFACTORY_USER # env variable for username to authentication protected repo
          server-password: FR_ARTIFACTORY_USER_ENCRYPTED_PASSWORD # env variable encrypted password to authentication protected repo
      - name: Call build-image
        uses: ./.github/actions/build-image
        with: 
          repositoryName: ${{ env.GITHUB_ACTION_REPOSITORY }}
          dockerBuildCommands: "make clean && make docker tag=$PR_NUMBER env=dev && make docker tag=$PR_NUMBER-prod"
          FR_ARTIFACTORY_USER: ${{ secrets.FR_ARTIFACTORY_USER }}
          FR_ARTIFACTORY_USER_ENCRYPTED_PASSWORD: ${{ secrets.FR_ARTIFACTORY_USER_ENCRYPTED_PASSWORD }}

  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    needs: build
    steps:
      - name: Call deploy-to-env
        uses: ./.github/actions/deploy-to-env
        with: 
          prNumber: ${{ env.PR_NUMBER }}
          serviceName: ${{ env.SERVICE_NAME }}
          cfTriggerName: ${{ env.CF_TRIGGER_NAME }}
          cfPipelineName: ${{ env.CF_PIPELINE_NAME }}
          cfPipelineBranch: ${{ env.CF_PIPELINE_BRANCH }}