name: Merge Notification
on:
  push:
    branches:
      - main
jobs:
  run_slack-notification:
    name: Merge Notification
    uses: SecureApiGateway/secure-api-gateway-ci/.github/workflows/reusable-slack-notification.yml@1389-standard-steps-for-workflows
    secrets: inherit